#!/usr/bin/env bash
set -euo pipefail

# Run like you would `./gradlew arguments`
# but now like `./gradlew_all_versions arguments`.

DRY_RUN=${DRY_RUN:-false}
SCALA2_12VERSION="2.12.15"
SCALA2_13VERSION="2.13.8"
SparkVersionsForBothScalaVersions=("3.3.0" "3.2.1" "3.2.0")
SparkVersionsForScala2_12=("3.1.3" "3.1.2" "3.1.1" "3.1.0" "3.0.3" "3.0.2" "3.0.1" "3.0.0")

echo Running for "$(expr ${#SparkVersionsForBothScalaVersions[@]} \* 2 + ${#SparkVersionsForScala2_12[@]}) versions of the library."

echo "Cleaning the project first."
if [ "$DRY_RUN" = false ]; then
  ./gradlew clean
fi

ARGS=("$@")
execute() {
  echo "running ./gradlew -Pspark=$SPARK -Pscala=$SCALA -PskipScalaTuplesInKotlin=$SKIP_SCALA_TUPLES -PenforceCleanJCP=true ${ARGS[*]}"
  if [ "$DRY_RUN" = false ]; then
    ./gradlew -Pspark="$SPARK" -Pscala="$SCALA" -PskipScalaTuplesInKotlin="$SKIP_SCALA_TUPLES" "${ARGS[@]}"
  fi
}

SCALA="$SCALA2_12VERSION"
SKIP_SCALA_TUPLES=false
for spark in "${SparkVersionsForScala2_12[@]}"; do
  SPARK="$spark"
  execute
  SKIP_SCALA_TUPLES=true
done


execute_for_both_scala_versions() {
  for spark in "${SparkVersionsForBothScalaVersions[@]}"; do
    SPARK="$spark"
    execute
    SKIP_SCALA_TUPLES=true
  done
}
SCALA="$SCALA2_12VERSION"
execute_for_both_scala_versions

SCALA="$SCALA2_13VERSION"
SKIP_SCALA_TUPLES=false
execute_for_both_scala_versions



