#!/usr/bin/env bash

# Run like you would `./gradlew arguments`
# but now like `./gradlew_all_versions arguments`.


SCALA2_12VERSION="2.12.15"
SCALA2_13VERSION="2.13.8"
SparkVersionsForBothScalaVersions=("3.3.0" "3.2.1" "3.2.0")
SparkVersionsForScala2_12=("3.1.3" "3.1.2" "3.1.1" "3.1.0" "3.0.3" "3.0.2" "3.0.1" "3.0.0")

echo Running for $(expr ${#SparkVersionsForBothScalaVersions[@]} \* 2 + ${#SparkVersionsForScala2_12[@]}) versions of the library.

ARGS=("$@")
execute() {
  echo "running ./gradlew -Pspark=$SPARK -Pscala=$SCALA ${ARGS[*]}"
  ./gradlew -Pspark="$SPARK" -Pscala="$SCALA" "${ARGS[@]}"
}

execute_for_both_scala_versions() {
  for spark in "${SparkVersionsForBothScalaVersions[@]}"; do
    SPARK="$spark"
    execute
  done
}
SCALA="$SCALA2_12VERSION"
execute_for_both_scala_versions
SCALA="$SCALA2_13VERSION"
execute_for_both_scala_versions

SCALA="$SCALA2_12VERSION"
for spark in "${SparkVersionsForScala2_12[@]}"; do
  SPARK="$spark"
  execute
done



