/*-
 * =LICENSE=
 * Kotlin Spark API: API for Spark 3.0+ (Scala 2.12)
 * ----------
 * Copyright (C) 2019 - 2021 JetBrains
 * ----------
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * =LICENSEEND=
 */
package org.jetbrains.kotlinx.spark.api.tuple

import scala.Product1
import scala.Product2
import scala.Product3
import scala.Product4
import scala.Product5
import scala.Product6
import scala.Product7
import scala.Product8
import scala.Product9
import scala.Product10
import scala.Product11
import scala.Product12
import scala.Product13
import scala.Product14
import scala.Product15
import scala.Product16
import scala.Product17
import scala.Product18
import scala.Product19
import scala.Product20
import scala.Product21
import scala.Product22

/**
 *
 * This file provides the operator functions to destructuring for Scala classes implementing ProductX, like Tuples.
 *
 * This means you can type `val (a, b, c, d) = yourTuple` to unpack its values,
 * similar to how [Pair], [Triple] and other data classes work in Kotlin.
 *
 * by Jolan Rensen, 18-02-2021
 */

operator fun <T> Product1<T>.component1(): T = this._1()
operator fun <T> Product2<T, *>.component1(): T = this._1()
operator fun <T> Product2<*, T>.component2(): T = this._2()
operator fun <T> Product3<T, *, *>.component1(): T = this._1()
operator fun <T> Product3<*, T, *>.component2(): T = this._2()
operator fun <T> Product3<*, *, T>.component3(): T = this._3()
operator fun <T> Product4<T, *, *, *>.component1(): T = this._1()
operator fun <T> Product4<*, T, *, *>.component2(): T = this._2()
operator fun <T> Product4<*, *, T, *>.component3(): T = this._3()
operator fun <T> Product4<*, *, *, T>.component4(): T = this._4()
operator fun <T> Product5<T, *, *, *, *>.component1(): T = this._1()
operator fun <T> Product5<*, T, *, *, *>.component2(): T = this._2()
operator fun <T> Product5<*, *, T, *, *>.component3(): T = this._3()
operator fun <T> Product5<*, *, *, T, *>.component4(): T = this._4()
operator fun <T> Product5<*, *, *, *, T>.component5(): T = this._5()
operator fun <T> Product6<T, *, *, *, *, *>.component1(): T = this._1()
operator fun <T> Product6<*, T, *, *, *, *>.component2(): T = this._2()
operator fun <T> Product6<*, *, T, *, *, *>.component3(): T = this._3()
operator fun <T> Product6<*, *, *, T, *, *>.component4(): T = this._4()
operator fun <T> Product6<*, *, *, *, T, *>.component5(): T = this._5()
operator fun <T> Product6<*, *, *, *, *, T>.component6(): T = this._6()
operator fun <T> Product7<T, *, *, *, *, *, *>.component1(): T = this._1()
operator fun <T> Product7<*, T, *, *, *, *, *>.component2(): T = this._2()
operator fun <T> Product7<*, *, T, *, *, *, *>.component3(): T = this._3()
operator fun <T> Product7<*, *, *, T, *, *, *>.component4(): T = this._4()
operator fun <T> Product7<*, *, *, *, T, *, *>.component5(): T = this._5()
operator fun <T> Product7<*, *, *, *, *, T, *>.component6(): T = this._6()
operator fun <T> Product7<*, *, *, *, *, *, T>.component7(): T = this._7()
operator fun <T> Product8<T, *, *, *, *, *, *, *>.component1(): T = this._1()
operator fun <T> Product8<*, T, *, *, *, *, *, *>.component2(): T = this._2()
operator fun <T> Product8<*, *, T, *, *, *, *, *>.component3(): T = this._3()
operator fun <T> Product8<*, *, *, T, *, *, *, *>.component4(): T = this._4()
operator fun <T> Product8<*, *, *, *, T, *, *, *>.component5(): T = this._5()
operator fun <T> Product8<*, *, *, *, *, T, *, *>.component6(): T = this._6()
operator fun <T> Product8<*, *, *, *, *, *, T, *>.component7(): T = this._7()
operator fun <T> Product8<*, *, *, *, *, *, *, T>.component8(): T = this._8()
operator fun <T> Product9<T, *, *, *, *, *, *, *, *>.component1(): T = this._1()
operator fun <T> Product9<*, T, *, *, *, *, *, *, *>.component2(): T = this._2()
operator fun <T> Product9<*, *, T, *, *, *, *, *, *>.component3(): T = this._3()
operator fun <T> Product9<*, *, *, T, *, *, *, *, *>.component4(): T = this._4()
operator fun <T> Product9<*, *, *, *, T, *, *, *, *>.component5(): T = this._5()
operator fun <T> Product9<*, *, *, *, *, T, *, *, *>.component6(): T = this._6()
operator fun <T> Product9<*, *, *, *, *, *, T, *, *>.component7(): T = this._7()
operator fun <T> Product9<*, *, *, *, *, *, *, T, *>.component8(): T = this._8()
operator fun <T> Product9<*, *, *, *, *, *, *, *, T>.component9(): T = this._9()
operator fun <T> Product10<T, *, *, *, *, *, *, *, *, *>.component1(): T = this._1()
operator fun <T> Product10<*, T, *, *, *, *, *, *, *, *>.component2(): T = this._2()
operator fun <T> Product10<*, *, T, *, *, *, *, *, *, *>.component3(): T = this._3()
operator fun <T> Product10<*, *, *, T, *, *, *, *, *, *>.component4(): T = this._4()
operator fun <T> Product10<*, *, *, *, T, *, *, *, *, *>.component5(): T = this._5()
operator fun <T> Product10<*, *, *, *, *, T, *, *, *, *>.component6(): T = this._6()
operator fun <T> Product10<*, *, *, *, *, *, T, *, *, *>.component7(): T = this._7()
operator fun <T> Product10<*, *, *, *, *, *, *, T, *, *>.component8(): T = this._8()
operator fun <T> Product10<*, *, *, *, *, *, *, *, T, *>.component9(): T = this._9()
operator fun <T> Product10<*, *, *, *, *, *, *, *, *, T>.component10(): T = this._10()
operator fun <T> Product11<T, *, *, *, *, *, *, *, *, *, *>.component1(): T = this._1()
operator fun <T> Product11<*, T, *, *, *, *, *, *, *, *, *>.component2(): T = this._2()
operator fun <T> Product11<*, *, T, *, *, *, *, *, *, *, *>.component3(): T = this._3()
operator fun <T> Product11<*, *, *, T, *, *, *, *, *, *, *>.component4(): T = this._4()
operator fun <T> Product11<*, *, *, *, T, *, *, *, *, *, *>.component5(): T = this._5()
operator fun <T> Product11<*, *, *, *, *, T, *, *, *, *, *>.component6(): T = this._6()
operator fun <T> Product11<*, *, *, *, *, *, T, *, *, *, *>.component7(): T = this._7()
operator fun <T> Product11<*, *, *, *, *, *, *, T, *, *, *>.component8(): T = this._8()
operator fun <T> Product11<*, *, *, *, *, *, *, *, T, *, *>.component9(): T = this._9()
operator fun <T> Product11<*, *, *, *, *, *, *, *, *, T, *>.component10(): T = this._10()
operator fun <T> Product11<*, *, *, *, *, *, *, *, *, *, T>.component11(): T = this._11()
operator fun <T> Product12<T, *, *, *, *, *, *, *, *, *, *, *>.component1(): T = this._1()
operator fun <T> Product12<*, T, *, *, *, *, *, *, *, *, *, *>.component2(): T = this._2()
operator fun <T> Product12<*, *, T, *, *, *, *, *, *, *, *, *>.component3(): T = this._3()
operator fun <T> Product12<*, *, *, T, *, *, *, *, *, *, *, *>.component4(): T = this._4()
operator fun <T> Product12<*, *, *, *, T, *, *, *, *, *, *, *>.component5(): T = this._5()
operator fun <T> Product12<*, *, *, *, *, T, *, *, *, *, *, *>.component6(): T = this._6()
operator fun <T> Product12<*, *, *, *, *, *, T, *, *, *, *, *>.component7(): T = this._7()
operator fun <T> Product12<*, *, *, *, *, *, *, T, *, *, *, *>.component8(): T = this._8()
operator fun <T> Product12<*, *, *, *, *, *, *, *, T, *, *, *>.component9(): T = this._9()
operator fun <T> Product12<*, *, *, *, *, *, *, *, *, T, *, *>.component10(): T = this._10()
operator fun <T> Product12<*, *, *, *, *, *, *, *, *, *, T, *>.component11(): T = this._11()
operator fun <T> Product12<*, *, *, *, *, *, *, *, *, *, *, T>.component12(): T = this._12()
operator fun <T> Product13<T, *, *, *, *, *, *, *, *, *, *, *, *>.component1(): T = this._1()
operator fun <T> Product13<*, T, *, *, *, *, *, *, *, *, *, *, *>.component2(): T = this._2()
operator fun <T> Product13<*, *, T, *, *, *, *, *, *, *, *, *, *>.component3(): T = this._3()
operator fun <T> Product13<*, *, *, T, *, *, *, *, *, *, *, *, *>.component4(): T = this._4()
operator fun <T> Product13<*, *, *, *, T, *, *, *, *, *, *, *, *>.component5(): T = this._5()
operator fun <T> Product13<*, *, *, *, *, T, *, *, *, *, *, *, *>.component6(): T = this._6()
operator fun <T> Product13<*, *, *, *, *, *, T, *, *, *, *, *, *>.component7(): T = this._7()
operator fun <T> Product13<*, *, *, *, *, *, *, T, *, *, *, *, *>.component8(): T = this._8()
operator fun <T> Product13<*, *, *, *, *, *, *, *, T, *, *, *, *>.component9(): T = this._9()
operator fun <T> Product13<*, *, *, *, *, *, *, *, *, T, *, *, *>.component10(): T = this._10()
operator fun <T> Product13<*, *, *, *, *, *, *, *, *, *, T, *, *>.component11(): T = this._11()
operator fun <T> Product13<*, *, *, *, *, *, *, *, *, *, *, T, *>.component12(): T = this._12()
operator fun <T> Product13<*, *, *, *, *, *, *, *, *, *, *, *, T>.component13(): T = this._13()
operator fun <T> Product14<T, *, *, *, *, *, *, *, *, *, *, *, *, *>.component1(): T = this._1()
operator fun <T> Product14<*, T, *, *, *, *, *, *, *, *, *, *, *, *>.component2(): T = this._2()
operator fun <T> Product14<*, *, T, *, *, *, *, *, *, *, *, *, *, *>.component3(): T = this._3()
operator fun <T> Product14<*, *, *, T, *, *, *, *, *, *, *, *, *, *>.component4(): T = this._4()
operator fun <T> Product14<*, *, *, *, T, *, *, *, *, *, *, *, *, *>.component5(): T = this._5()
operator fun <T> Product14<*, *, *, *, *, T, *, *, *, *, *, *, *, *>.component6(): T = this._6()
operator fun <T> Product14<*, *, *, *, *, *, T, *, *, *, *, *, *, *>.component7(): T = this._7()
operator fun <T> Product14<*, *, *, *, *, *, *, T, *, *, *, *, *, *>.component8(): T = this._8()
operator fun <T> Product14<*, *, *, *, *, *, *, *, T, *, *, *, *, *>.component9(): T = this._9()
operator fun <T> Product14<*, *, *, *, *, *, *, *, *, T, *, *, *, *>.component10(): T = this._10()
operator fun <T> Product14<*, *, *, *, *, *, *, *, *, *, T, *, *, *>.component11(): T = this._11()
operator fun <T> Product14<*, *, *, *, *, *, *, *, *, *, *, T, *, *>.component12(): T = this._12()
operator fun <T> Product14<*, *, *, *, *, *, *, *, *, *, *, *, T, *>.component13(): T = this._13()
operator fun <T> Product14<*, *, *, *, *, *, *, *, *, *, *, *, *, T>.component14(): T = this._14()
operator fun <T> Product15<T, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component1(): T = this._1()
operator fun <T> Product15<*, T, *, *, *, *, *, *, *, *, *, *, *, *, *>.component2(): T = this._2()
operator fun <T> Product15<*, *, T, *, *, *, *, *, *, *, *, *, *, *, *>.component3(): T = this._3()
operator fun <T> Product15<*, *, *, T, *, *, *, *, *, *, *, *, *, *, *>.component4(): T = this._4()
operator fun <T> Product15<*, *, *, *, T, *, *, *, *, *, *, *, *, *, *>.component5(): T = this._5()
operator fun <T> Product15<*, *, *, *, *, T, *, *, *, *, *, *, *, *, *>.component6(): T = this._6()
operator fun <T> Product15<*, *, *, *, *, *, T, *, *, *, *, *, *, *, *>.component7(): T = this._7()
operator fun <T> Product15<*, *, *, *, *, *, *, T, *, *, *, *, *, *, *>.component8(): T = this._8()
operator fun <T> Product15<*, *, *, *, *, *, *, *, T, *, *, *, *, *, *>.component9(): T = this._9()
operator fun <T> Product15<*, *, *, *, *, *, *, *, *, T, *, *, *, *, *>.component10(): T = this._10()
operator fun <T> Product15<*, *, *, *, *, *, *, *, *, *, T, *, *, *, *>.component11(): T = this._11()
operator fun <T> Product15<*, *, *, *, *, *, *, *, *, *, *, T, *, *, *>.component12(): T = this._12()
operator fun <T> Product15<*, *, *, *, *, *, *, *, *, *, *, *, T, *, *>.component13(): T = this._13()
operator fun <T> Product15<*, *, *, *, *, *, *, *, *, *, *, *, *, T, *>.component14(): T = this._14()
operator fun <T> Product15<*, *, *, *, *, *, *, *, *, *, *, *, *, *, T>.component15(): T = this._15()
operator fun <T> Product16<T, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component1(): T = this._1()
operator fun <T> Product16<*, T, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component2(): T = this._2()
operator fun <T> Product16<*, *, T, *, *, *, *, *, *, *, *, *, *, *, *, *>.component3(): T = this._3()
operator fun <T> Product16<*, *, *, T, *, *, *, *, *, *, *, *, *, *, *, *>.component4(): T = this._4()
operator fun <T> Product16<*, *, *, *, T, *, *, *, *, *, *, *, *, *, *, *>.component5(): T = this._5()
operator fun <T> Product16<*, *, *, *, *, T, *, *, *, *, *, *, *, *, *, *>.component6(): T = this._6()
operator fun <T> Product16<*, *, *, *, *, *, T, *, *, *, *, *, *, *, *, *>.component7(): T = this._7()
operator fun <T> Product16<*, *, *, *, *, *, *, T, *, *, *, *, *, *, *, *>.component8(): T = this._8()
operator fun <T> Product16<*, *, *, *, *, *, *, *, T, *, *, *, *, *, *, *>.component9(): T = this._9()
operator fun <T> Product16<*, *, *, *, *, *, *, *, *, T, *, *, *, *, *, *>.component10(): T = this._10()
operator fun <T> Product16<*, *, *, *, *, *, *, *, *, *, T, *, *, *, *, *>.component11(): T = this._11()
operator fun <T> Product16<*, *, *, *, *, *, *, *, *, *, *, T, *, *, *, *>.component12(): T = this._12()
operator fun <T> Product16<*, *, *, *, *, *, *, *, *, *, *, *, T, *, *, *>.component13(): T = this._13()
operator fun <T> Product16<*, *, *, *, *, *, *, *, *, *, *, *, *, T, *, *>.component14(): T = this._14()
operator fun <T> Product16<*, *, *, *, *, *, *, *, *, *, *, *, *, *, T, *>.component15(): T = this._15()
operator fun <T> Product16<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, T>.component16(): T = this._16()
operator fun <T> Product17<T, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component1(): T = this._1()
operator fun <T> Product17<*, T, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component2(): T = this._2()
operator fun <T> Product17<*, *, T, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component3(): T = this._3()
operator fun <T> Product17<*, *, *, T, *, *, *, *, *, *, *, *, *, *, *, *, *>.component4(): T = this._4()
operator fun <T> Product17<*, *, *, *, T, *, *, *, *, *, *, *, *, *, *, *, *>.component5(): T = this._5()
operator fun <T> Product17<*, *, *, *, *, T, *, *, *, *, *, *, *, *, *, *, *>.component6(): T = this._6()
operator fun <T> Product17<*, *, *, *, *, *, T, *, *, *, *, *, *, *, *, *, *>.component7(): T = this._7()
operator fun <T> Product17<*, *, *, *, *, *, *, T, *, *, *, *, *, *, *, *, *>.component8(): T = this._8()
operator fun <T> Product17<*, *, *, *, *, *, *, *, T, *, *, *, *, *, *, *, *>.component9(): T = this._9()
operator fun <T> Product17<*, *, *, *, *, *, *, *, *, T, *, *, *, *, *, *, *>.component10(): T = this._10()
operator fun <T> Product17<*, *, *, *, *, *, *, *, *, *, T, *, *, *, *, *, *>.component11(): T = this._11()
operator fun <T> Product17<*, *, *, *, *, *, *, *, *, *, *, T, *, *, *, *, *>.component12(): T = this._12()
operator fun <T> Product17<*, *, *, *, *, *, *, *, *, *, *, *, T, *, *, *, *>.component13(): T = this._13()
operator fun <T> Product17<*, *, *, *, *, *, *, *, *, *, *, *, *, T, *, *, *>.component14(): T = this._14()
operator fun <T> Product17<*, *, *, *, *, *, *, *, *, *, *, *, *, *, T, *, *>.component15(): T = this._15()
operator fun <T> Product17<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, T, *>.component16(): T = this._16()
operator fun <T> Product17<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, T>.component17(): T = this._17()
operator fun <T> Product18<T, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component1(): T = this._1()
operator fun <T> Product18<*, T, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component2(): T = this._2()
operator fun <T> Product18<*, *, T, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component3(): T = this._3()
operator fun <T> Product18<*, *, *, T, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component4(): T = this._4()
operator fun <T> Product18<*, *, *, *, T, *, *, *, *, *, *, *, *, *, *, *, *, *>.component5(): T = this._5()
operator fun <T> Product18<*, *, *, *, *, T, *, *, *, *, *, *, *, *, *, *, *, *>.component6(): T = this._6()
operator fun <T> Product18<*, *, *, *, *, *, T, *, *, *, *, *, *, *, *, *, *, *>.component7(): T = this._7()
operator fun <T> Product18<*, *, *, *, *, *, *, T, *, *, *, *, *, *, *, *, *, *>.component8(): T = this._8()
operator fun <T> Product18<*, *, *, *, *, *, *, *, T, *, *, *, *, *, *, *, *, *>.component9(): T = this._9()
operator fun <T> Product18<*, *, *, *, *, *, *, *, *, T, *, *, *, *, *, *, *, *>.component10(): T = this._10()
operator fun <T> Product18<*, *, *, *, *, *, *, *, *, *, T, *, *, *, *, *, *, *>.component11(): T = this._11()
operator fun <T> Product18<*, *, *, *, *, *, *, *, *, *, *, T, *, *, *, *, *, *>.component12(): T = this._12()
operator fun <T> Product18<*, *, *, *, *, *, *, *, *, *, *, *, T, *, *, *, *, *>.component13(): T = this._13()
operator fun <T> Product18<*, *, *, *, *, *, *, *, *, *, *, *, *, T, *, *, *, *>.component14(): T = this._14()
operator fun <T> Product18<*, *, *, *, *, *, *, *, *, *, *, *, *, *, T, *, *, *>.component15(): T = this._15()
operator fun <T> Product18<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, T, *, *>.component16(): T = this._16()
operator fun <T> Product18<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, T, *>.component17(): T = this._17()
operator fun <T> Product18<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, T>.component18(): T = this._18()
operator fun <T> Product19<T, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component1(): T = this._1()
operator fun <T> Product19<*, T, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component2(): T = this._2()
operator fun <T> Product19<*, *, T, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component3(): T = this._3()
operator fun <T> Product19<*, *, *, T, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component4(): T = this._4()
operator fun <T> Product19<*, *, *, *, T, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component5(): T = this._5()
operator fun <T> Product19<*, *, *, *, *, T, *, *, *, *, *, *, *, *, *, *, *, *, *>.component6(): T = this._6()
operator fun <T> Product19<*, *, *, *, *, *, T, *, *, *, *, *, *, *, *, *, *, *, *>.component7(): T = this._7()
operator fun <T> Product19<*, *, *, *, *, *, *, T, *, *, *, *, *, *, *, *, *, *, *>.component8(): T = this._8()
operator fun <T> Product19<*, *, *, *, *, *, *, *, T, *, *, *, *, *, *, *, *, *, *>.component9(): T = this._9()
operator fun <T> Product19<*, *, *, *, *, *, *, *, *, T, *, *, *, *, *, *, *, *, *>.component10(): T = this._10()
operator fun <T> Product19<*, *, *, *, *, *, *, *, *, *, T, *, *, *, *, *, *, *, *>.component11(): T = this._11()
operator fun <T> Product19<*, *, *, *, *, *, *, *, *, *, *, T, *, *, *, *, *, *, *>.component12(): T = this._12()
operator fun <T> Product19<*, *, *, *, *, *, *, *, *, *, *, *, T, *, *, *, *, *, *>.component13(): T = this._13()
operator fun <T> Product19<*, *, *, *, *, *, *, *, *, *, *, *, *, T, *, *, *, *, *>.component14(): T = this._14()
operator fun <T> Product19<*, *, *, *, *, *, *, *, *, *, *, *, *, *, T, *, *, *, *>.component15(): T = this._15()
operator fun <T> Product19<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, T, *, *, *>.component16(): T = this._16()
operator fun <T> Product19<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, T, *, *>.component17(): T = this._17()
operator fun <T> Product19<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, T, *>.component18(): T = this._18()
operator fun <T> Product19<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, T>.component19(): T = this._19()
operator fun <T> Product20<T, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component1(): T = this._1()
operator fun <T> Product20<*, T, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component2(): T = this._2()
operator fun <T> Product20<*, *, T, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component3(): T = this._3()
operator fun <T> Product20<*, *, *, T, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component4(): T = this._4()
operator fun <T> Product20<*, *, *, *, T, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component5(): T = this._5()
operator fun <T> Product20<*, *, *, *, *, T, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component6(): T = this._6()
operator fun <T> Product20<*, *, *, *, *, *, T, *, *, *, *, *, *, *, *, *, *, *, *, *>.component7(): T = this._7()
operator fun <T> Product20<*, *, *, *, *, *, *, T, *, *, *, *, *, *, *, *, *, *, *, *>.component8(): T = this._8()
operator fun <T> Product20<*, *, *, *, *, *, *, *, T, *, *, *, *, *, *, *, *, *, *, *>.component9(): T = this._9()
operator fun <T> Product20<*, *, *, *, *, *, *, *, *, T, *, *, *, *, *, *, *, *, *, *>.component10(): T = this._10()
operator fun <T> Product20<*, *, *, *, *, *, *, *, *, *, T, *, *, *, *, *, *, *, *, *>.component11(): T = this._11()
operator fun <T> Product20<*, *, *, *, *, *, *, *, *, *, *, T, *, *, *, *, *, *, *, *>.component12(): T = this._12()
operator fun <T> Product20<*, *, *, *, *, *, *, *, *, *, *, *, T, *, *, *, *, *, *, *>.component13(): T = this._13()
operator fun <T> Product20<*, *, *, *, *, *, *, *, *, *, *, *, *, T, *, *, *, *, *, *>.component14(): T = this._14()
operator fun <T> Product20<*, *, *, *, *, *, *, *, *, *, *, *, *, *, T, *, *, *, *, *>.component15(): T = this._15()
operator fun <T> Product20<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, T, *, *, *, *>.component16(): T = this._16()
operator fun <T> Product20<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, T, *, *, *>.component17(): T = this._17()
operator fun <T> Product20<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, T, *, *>.component18(): T = this._18()
operator fun <T> Product20<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, T, *>.component19(): T = this._19()
operator fun <T> Product20<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, T>.component20(): T = this._20()
operator fun <T> Product21<T, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component1(): T = this._1()
operator fun <T> Product21<*, T, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component2(): T = this._2()
operator fun <T> Product21<*, *, T, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component3(): T = this._3()
operator fun <T> Product21<*, *, *, T, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component4(): T = this._4()
operator fun <T> Product21<*, *, *, *, T, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component5(): T = this._5()
operator fun <T> Product21<*, *, *, *, *, T, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component6(): T = this._6()
operator fun <T> Product21<*, *, *, *, *, *, T, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component7(): T = this._7()
operator fun <T> Product21<*, *, *, *, *, *, *, T, *, *, *, *, *, *, *, *, *, *, *, *, *>.component8(): T = this._8()
operator fun <T> Product21<*, *, *, *, *, *, *, *, T, *, *, *, *, *, *, *, *, *, *, *, *>.component9(): T = this._9()
operator fun <T> Product21<*, *, *, *, *, *, *, *, *, T, *, *, *, *, *, *, *, *, *, *, *>.component10(): T = this._10()
operator fun <T> Product21<*, *, *, *, *, *, *, *, *, *, T, *, *, *, *, *, *, *, *, *, *>.component11(): T = this._11()
operator fun <T> Product21<*, *, *, *, *, *, *, *, *, *, *, T, *, *, *, *, *, *, *, *, *>.component12(): T = this._12()
operator fun <T> Product21<*, *, *, *, *, *, *, *, *, *, *, *, T, *, *, *, *, *, *, *, *>.component13(): T = this._13()
operator fun <T> Product21<*, *, *, *, *, *, *, *, *, *, *, *, *, T, *, *, *, *, *, *, *>.component14(): T = this._14()
operator fun <T> Product21<*, *, *, *, *, *, *, *, *, *, *, *, *, *, T, *, *, *, *, *, *>.component15(): T = this._15()
operator fun <T> Product21<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, T, *, *, *, *, *>.component16(): T = this._16()
operator fun <T> Product21<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, T, *, *, *, *>.component17(): T = this._17()
operator fun <T> Product21<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, T, *, *, *>.component18(): T = this._18()
operator fun <T> Product21<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, T, *, *>.component19(): T = this._19()
operator fun <T> Product21<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, T, *>.component20(): T = this._20()
operator fun <T> Product21<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, T>.component21(): T = this._21()
operator fun <T> Product22<T, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component1(): T = this._1()
operator fun <T> Product22<*, T, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component2(): T = this._2()
operator fun <T> Product22<*, *, T, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component3(): T = this._3()
operator fun <T> Product22<*, *, *, T, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component4(): T = this._4()
operator fun <T> Product22<*, *, *, *, T, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component5(): T = this._5()
operator fun <T> Product22<*, *, *, *, *, T, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component6(): T = this._6()
operator fun <T> Product22<*, *, *, *, *, *, T, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component7(): T = this._7()
operator fun <T> Product22<*, *, *, *, *, *, *, T, *, *, *, *, *, *, *, *, *, *, *, *, *, *>.component8(): T = this._8()
operator fun <T> Product22<*, *, *, *, *, *, *, *, T, *, *, *, *, *, *, *, *, *, *, *, *, *>.component9(): T = this._9()
operator fun <T> Product22<*, *, *, *, *, *, *, *, *, T, *, *, *, *, *, *, *, *, *, *, *, *>.component10(): T = this._10()
operator fun <T> Product22<*, *, *, *, *, *, *, *, *, *, T, *, *, *, *, *, *, *, *, *, *, *>.component11(): T = this._11()
operator fun <T> Product22<*, *, *, *, *, *, *, *, *, *, *, T, *, *, *, *, *, *, *, *, *, *>.component12(): T = this._12()
operator fun <T> Product22<*, *, *, *, *, *, *, *, *, *, *, *, T, *, *, *, *, *, *, *, *, *>.component13(): T = this._13()
operator fun <T> Product22<*, *, *, *, *, *, *, *, *, *, *, *, *, T, *, *, *, *, *, *, *, *>.component14(): T = this._14()
operator fun <T> Product22<*, *, *, *, *, *, *, *, *, *, *, *, *, *, T, *, *, *, *, *, *, *>.component15(): T = this._15()
operator fun <T> Product22<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, T, *, *, *, *, *, *>.component16(): T = this._16()
operator fun <T> Product22<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, T, *, *, *, *, *>.component17(): T = this._17()
operator fun <T> Product22<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, T, *, *, *, *>.component18(): T = this._18()
operator fun <T> Product22<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, T, *, *, *>.component19(): T = this._19()
operator fun <T> Product22<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, T, *, *>.component20(): T = this._20()
operator fun <T> Product22<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, T, *>.component21(): T = this._21()
operator fun <T> Product22<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, T>.component22(): T = this._22()
